/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account. The first account needs no invite code and becomes
         *     admin; every later one consumes an unused invite code.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserBody"];
                    };
                };
                /** @description Invite code missing, unknown, or already used */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Username already taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Username or password does not meet the requirements */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                /** @description Too many attempts from this address; try again later */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with username and password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserBody"];
                    };
                };
                /** @description Unknown username or wrong password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too many attempts from this address; try again later */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated account. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["UserBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API tokens. Only the display prefix is available after creation. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["TokenBody"][];
                    };
                };
            };
        };
        put?: never;
        /** Create an API token for an agent. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateTokenRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["CreatedTokenBody"];
                    };
                };
                /** @description Name is empty */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API token. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No token with this id on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invite codes and who used them. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["InviteBody"][];
                    };
                };
                /** @description Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Mint an invite code. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["InviteBody"];
                    };
                };
                /** @description Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an unused invite code. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No unused invite with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your projects, newest activity first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ProjectBody"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/aliases/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Point another name at this project. A push naming the alias lands in the
         *     project, so `openlv` and `open-lavatory` do not become two piles.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project: string;
                    alias: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The alias is already a project of its own, or points somewhere else */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                /** @description Not a valid slug shape */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        post?: never;
        /** Stop resolving this name. Documents already in the project stay put. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project: string;
                    alias: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The alias is already a project of its own, or points somewhere else */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
                /** @description Not a valid slug shape */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an empty project, along with its aliases and icons.
         * @description Named exactly, never through an alias: deleting `openlv` should not take
         *     `open-lavatory` with it. A project holding documents is refused rather
         *     than emptied, because unfiling a pile of documents is not something a
         *     delete button should do quietly.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No project of this name on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The project still holds documents, which would be left unfiled */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/favicon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A project's favicon. Owner only, like everything else about a document. */
        get: {
            parameters: {
                query?: {
                    scheme?: components["schemas"]["Scheme"];
                };
                header?: never;
                path: {
                    project: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        "CONTENT-TYPE": string;
                        "CACHE-CONTROL": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description No such project, or no favicon in this colour scheme */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Upload a project favicon. Every document in the project then serves it,
         *     so a reader's tab says which project they are looking at.
         */
        put: {
            parameters: {
                query?: {
                    scheme?: components["schemas"]["Scheme"];
                };
                header?: never;
                path: {
                    project: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No project of this name on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not an accepted image type, or larger than 64KB */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document metadata and its revision index. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DocumentDetailBody"];
                    };
                };
                /** @description No document with this slug on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Push a document. The first push of a slug creates the document and
         *     mints its public id; every later push appends a revision at the same
         *     URL.
         */
        put: {
            parameters: {
                query?: {
                    title?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "text/html": string;
                    "multipart/form-data": string;
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PushedBody"];
                    };
                };
                /** @description Slug must match [a-z0-9-]{1,64} */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct a document's title, project or tags without pushing a revision.
         *     This is how documents pushed before projects existed get sorted.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["PatchRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DocumentDetailBody"];
                    };
                };
                /** @description No document with this slug on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project or a tag does not fit its shape */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your documents. */
        get: {
            parameters: {
                query?: {
                    /** @description Restrict to one project. An alias resolves to the project it names. */
                    project?: string;
                    /** @description Newest first; useful for reading only the last few of a project. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["DocumentBody"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The latest revision's HTML. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        "CONTENT-SECURITY-POLICY": string;
                        "X-CONTENT-TYPE-OPTIONS": string;
                        "REFERRER-POLICY": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html; charset=utf-8": string;
                    };
                };
                /** @description No such document or revision on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/revisions/{revision}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The HTML as of a specific revision. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                    revision: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        "CONTENT-SECURITY-POLICY": string;
                        "X-CONTENT-TYPE-OPTIONS": string;
                        "REFERRER-POLICY": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html; charset=utf-8": string;
                    };
                };
                /** @description No such document or revision on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish the document behind a password. Calling this again rotates the
         *     password and invalidates every outstanding visitor cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["PublishRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PublishedBody"];
                    };
                };
                /** @description No document with this slug on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Password must not be empty */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A revision's thumbnail. Owner only, and never referenced from the public
         *     URL: a thumbnail past the password gate would undo the gate.
         */
        get: {
            parameters: {
                query?: {
                    scheme?: components["schemas"]["Scheme"];
                    revision?: number;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        "CONTENT-TYPE": string;
                        "CACHE-CONTROL": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description No such revision, or its thumbnail is not rendered yet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/preview/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue the latest revision's thumbnail to be rendered again.
         * @description A stored preview is never revisited on its own, so a thumbnail captured
         *     by a broken renderer, or before the page's own assets existed, would
         *     otherwise stay wrong forever.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No document with this slug on this account, or it has no revisions */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The latest revision's questions, each with the owner's answer or null. */
        get: {
            parameters: {
                query?: {
                    revision?: number;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AnsweredQuestion"][];
                    };
                };
                /** @description No document with this slug on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/answers/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record one answer. Accepts a browser session or a scoped answer key,
         *     never a normal API token.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["AnswerRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        "ACCESS-CONTROL-ALLOW-ORIGIN": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Answer"];
                    };
                };
                /** @description No such document, or the latest revision does not ask this question */
                404: {
                    headers: {
                        "ACCESS-CONTROL-ALLOW-ORIGIN": string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The answer does not fit the question that was asked */
                422: {
                    headers: {
                        "ACCESS-CONTROL-ALLOW-ORIGIN": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": string;
                    };
                };
            };
        };
        post?: never;
        /** Withdraw an answer, returning the question to unanswered. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        "ACCESS-CONTROL-ALLOW-ORIGIN": string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: {
                    headers: {
                        "ACCESS-CONTROL-ALLOW-ORIGIN": string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * CORS preflight for the two answer routes. The widget calls from the
         *     document's opaque origin, which presents `Origin: null`.
         */
        options: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    _slug: string;
                    _key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        "ACCESS-CONTROL-ALLOW-ORIGIN": string;
                        "ACCESS-CONTROL-ALLOW-HEADERS": string;
                        "ACCESS-CONTROL-ALLOW-METHODS": string;
                        "ACCESS-CONTROL-MAX-AGE": string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{slug}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take the document off the public URL again. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No document with this slug on this account */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            selected: string[];
            other_text?: string;
            notes?: string;
            answered_at: string;
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** @description Declared option values, or the reserved `other` for a written answer. */
            selected: string[];
            other_text?: string;
            notes?: string;
        };
        /**
         * AnsweredQuestion
         * @description A question with whatever the owner decided about it. One shape for the
         *     widget, the SPA and the MCP tool.
         */
        AnsweredQuestion: {
            /** @description Stable across revisions; an answer is keyed by this, not by revision. */
            key: string;
            prompt: string;
            detail?: string;
            /** @description An element id in the document; the widget places the card after it. */
            anchor?: string;
            multiple: boolean;
            options: components["schemas"]["QuestionOption"][];
            answer?: components["schemas"]["Answer"];
        };
        /** CreateTokenRequest */
        CreateTokenRequest: {
            name: string;
        };
        /** CreatedTokenBody */
        CreatedTokenBody: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description The full token. Shown exactly once; only its hash is stored. */
            token: string;
        };
        /** DocumentBody */
        DocumentBody: {
            id: string;
            slug: string;
            title?: string;
            project?: string;
            tags: string[];
            published: boolean;
            /** Format: int64 */
            revision_count: number;
            /** Format: int64 */
            latest_revision: number;
            /**
             * Format: int64
             * @description Questions the latest revision asks, and how many carry an answer
             */
            questions_total: number;
            /** Format: int64 */
            questions_answered: number;
            /** @description When the newest revision was pushed; the list sorts by this */
            last_pushed_at: string;
            created_at: string;
            updated_at: string;
            url: string;
        };
        /** DocumentDetailBody */
        DocumentDetailBody: {
            id: string;
            slug: string;
            title?: string;
            project?: string;
            tags: string[];
            published: boolean;
            created_at: string;
            updated_at: string;
            url: string;
            revisions: components["schemas"]["RevisionBody"][];
            questions: components["schemas"]["AnsweredQuestion"][];
        };
        /** InviteBody */
        InviteBody: {
            /** Format: int64 */
            id: number;
            code: string;
            created_at: string;
            used_at?: string;
            used_by?: string;
        };
        /** LoginRequest */
        LoginRequest: {
            username: string;
            password: string;
        };
        /**
         * PatchRequest
         * @description Fields a document owner may correct after the fact. Omitted leaves the
         *     stored value alone, which is what makes "no backfill" workable for the
         *     documents pushed before projects existed.
         */
        PatchRequest: {
            title?: string;
            project?: string;
            tags?: string[];
        };
        /** ProjectBody */
        ProjectBody: {
            slug: string;
            /** @description Other names that resolve to this project on push */
            aliases: string[];
            /** Format: int64 */
            document_count: number;
            /** @description Newest push in the project, so the list can sort by activity */
            last_pushed_at?: string;
            has_favicon_light: boolean;
            has_favicon_dark: boolean;
        };
        /** PublishRequest */
        PublishRequest: {
            password: string;
        };
        /** PublishedBody */
        PublishedBody: {
            url: string;
        };
        /** PushedBody */
        PushedBody: {
            /** @description Server-minted public document id, stable across revisions */
            id: string;
            slug: string;
            /** Format: int64 */
            revision: number;
            /** Format: int64 */
            size_bytes: number;
            url: string;
        };
        /** QuestionOption */
        QuestionOption: {
            value: string;
            label: string;
            detail?: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            username: string;
            password: string;
            invite_code?: string;
        };
        /** RevisionBody */
        RevisionBody: {
            /** Format: int64 */
            revision: number;
            /** Format: int64 */
            size_bytes: number;
            created_at: string;
        };
        /** @enum {string} */
        Scheme: "light" | "dark";
        /** TokenBody */
        TokenBody: {
            /** Format: int64 */
            id: number;
            name: string;
            token_prefix: string;
            created_at: string;
            last_used_at?: string;
        };
        /** UserBody */
        UserBody: {
            /** Format: int64 */
            id: number;
            username: string;
            is_admin: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
