/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthInvitesRouteImport } from './routes/_auth.invites'
import { Route as AuthTokensRouteImport } from './routes/_auth.tokens'
import { Route as AuthDocumentsSlugRouteImport } from './routes/_auth.documents.$slug'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth.projects.index'
import { Route as AuthProjectsProjectRouteImport } from './routes/_auth.projects.$project'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvitesRoute = AuthInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTokensRoute = AuthTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocumentsSlugRoute = AuthDocumentsSlugRouteImport.update({
  id: '/documents/$slug',
  path: '/documents/$slug',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectRoute = AuthProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/invites': typeof AuthInvitesRoute
  '/tokens': typeof AuthTokensRoute
  '/documents/$slug': typeof AuthDocumentsSlugRoute
  '/projects/$project': typeof AuthProjectsProjectRoute
  '/projects/': typeof AuthProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/invites': typeof AuthInvitesRoute
  '/tokens': typeof AuthTokensRoute
  '/': typeof AuthIndexRoute
  '/documents/$slug': typeof AuthDocumentsSlugRoute
  '/projects/$project': typeof AuthProjectsProjectRoute
  '/projects': typeof AuthProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/invites': typeof AuthInvitesRoute
  '/_auth/tokens': typeof AuthTokensRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/documents/$slug': typeof AuthDocumentsSlugRoute
  '/_auth/projects/$project': typeof AuthProjectsProjectRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/invites'
    | '/tokens'
    | '/documents/$slug'
    | '/projects/$project'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/invites'
    | '/tokens'
    | '/'
    | '/documents/$slug'
    | '/projects/$project'
    | '/projects'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/invites'
    | '/_auth/tokens'
    | '/_auth/'
    | '/_auth/documents/$slug'
    | '/_auth/projects/$project'
    | '/_auth/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invites': {
      id: '/_auth/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthInvitesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tokens': {
      id: '/_auth/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthTokensRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/documents/$slug': {
      id: '/_auth/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/documents/$slug'
      preLoaderRoute: typeof AuthDocumentsSlugRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$project': {
      id: '/_auth/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof AuthProjectsProjectRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthInvitesRoute: typeof AuthInvitesRoute
  AuthTokensRoute: typeof AuthTokensRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDocumentsSlugRoute: typeof AuthDocumentsSlugRoute
  AuthProjectsProjectRoute: typeof AuthProjectsProjectRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthInvitesRoute: AuthInvitesRoute,
  AuthTokensRoute: AuthTokensRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthDocumentsSlugRoute: AuthDocumentsSlugRoute,
  AuthProjectsProjectRoute: AuthProjectsProjectRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
